Controllers/ControlsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ControlsController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Text"] = "";
            return View();
        }

        [HttpGet]
        public IActionResult TextBox()
        {
            ViewData["Method"] = "Get";
            return View();
        }

        [HttpPost]
        public IActionResult TextBox(string text)
        {
            ViewData["Method"] = "Post";
            
            ViewData["Text"] = text;

            return View();
        }

        [HttpGet]
        public IActionResult TextArea()
        {
            ViewData["Method"] = "Get";
            return View();
        }
        [HttpPost]
        public IActionResult TextArea(string text)
        {
            ViewData["Method"] = "Post";
            ViewData["Text"] = text;

            return View();
        }

        [HttpGet]
        public IActionResult CheckBox()
        {
            ViewData["Method"] = "Get";
            return View();
        }
        [HttpPost]
        public IActionResult CheckBox(string Enable)
        {
            ViewData["Method"] = "Post";
            
            if (Enable == "true") ViewData["Text"] = "True";
            else ViewData["Text"] = "False";
            return View();
        }

        [HttpGet]
        public IActionResult Radio()
        {
            ViewData["Method"] = "Get";
            return View();
        }

        [HttpPost]
        public IActionResult Radio(string month)
        {
            ViewData["Method"] = "Post";
            ViewData["Text"] = month;

            return View();
        }

        [HttpGet]
        public IActionResult DropDownList()
        {
            ViewData["Method"] = "Get";
            return View();
        }
        [HttpPost]
        public IActionResult DropDownList(string month)
        {
            ViewData["Method"] = "Post";
            ViewData["Text"] = month;
            return View();
        }

        [HttpGet]
        public IActionResult ListBox()
        {
            ViewData["Method"] = "Get";
            return View();
        }
        [HttpPost]
        public IActionResult ListBox(string month)
        {
            ViewData["Method"] = "Post";
            ViewData["Text"] = month;
            return View();
        }
    }
}

Controllers/MockupsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;


namespace WebApplication1.Controllers
{
    public class MockupsController : Controller
    {
        static UsersInfo Person = new UsersInfo();
        public IActionResult Index(string Action) {
            if (Action == "Verify") ViewData["Reset"] = "Instructions has been sent on your email. Check and follow it!";
            else ViewData["Reset"] = "";
            return View();
        }

        [HttpGet]
        public IActionResult SignUp()
        {            
            ViewData["SignUpStep"] = "1";

            var days = new List<int>();
            var years = new List<int>();

            for (int i = 1; i < 32; i++)
                days.Add(i);

            for (int i = 1900; i < 2023; i++)
                years.Add(i);
           
            ViewBag.Days = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(days);
            ViewBag.Years = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(years);
            
            return View();        
        }

        [HttpPost]
        public IActionResult SignUp(string days, string month, string years, string Gender, string FName, string LName)
        {
            ViewData["InvalidDate"] = "";

                if (ModelState.IsValid)
                {                   
                    ViewData["SignUpStep"] = "2";

                    int day = Int32.Parse(days);
                    int year = Int32.Parse(years);

                    if (day > 28 && (month == "February") && (year % 4 != 0))                   
                    {
                        days = 28.ToString();
                        ViewData["InvalidDate"] = "Incorrect date was chosen. System suppose "+ days+" "+month+" " + years +" is correct date. If it is wrong, return to the previous page and correct your birth date";
                    }
                        
                    else if (day > 29 && (month == "February") && (year % 4 == 0))
                    {
                        days = 29.ToString();
                        ViewData["InvalidDate"] = "Incorrect date was chosen. System suppose " + days + " " + month + " " + years + " is correct date. If it is wrong, return to the previous page and correct your birth date"; ;
                    }

                    if (day > 30 && ( month == "April" || month == "June" || month == "September" || month == "November" ))
                    {
                        days = 30.ToString();
                        ViewData["InvalidDate"] = "Incorrect date was chosen. System suppose " + days + " " + month + " " + years + " is correct date. If it is wrong, return to the previous page and correct your birth date"; ;
                    }


                    Person.FName = FName;
                    Person.LName = LName;
                    Person.BDay = days;
                    Person.BMonth = month;
                    Person.BYear = years;
                    Person.Gender = Gender;

                    return View();

                }
                else
                {
                    ViewData["SignUpStep"] = "1";
                    return View();
                }
            
        }
        public IActionResult SignUpCredentials(string Email, string Password, string Remember, string PasswordConfirm)
        {
            Person.EMail = Email;
            Person.Password = Password;
            Person.PasswordConfirm = PasswordConfirm;
            Person.Remembered = Remember;

            Person.ListOfUsers.Add(Person);

            return View(Person);
        }

        [HttpGet]
        public IActionResult Reset()
        {          
            ViewData["Method"] = "Get";           
            return View();
        }

        [HttpPost]
        public IActionResult Reset(string EMail)
        {           
            ViewData["Method"] = "Post";
            return View();
        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult CheckEmail(string EMail)
        {          
            foreach (UsersInfo person in Person.ListOfUsers)
            {              
                if (EMail == person.EMail)                    
                        return Json(false);                  
            }
            return Json(true);
        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult CheckEmailReset(string EMailForReset)
        {            
            foreach (UsersInfo person in Person.ListOfUsers)
            {              
                if (EMailForReset == person.EMail)                    
                        return Json(true);                   
            }                    
            return Json(false);          
        }      
    }
}

Views/Shared/_Layout.cshtml



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />

    <style>
    header {background-color: black; padding:5px;}
    .headlinks {color: grey; text-decoration: none;} 
    </style>
</head>

<body>
    <header>
        <nav @*class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"*@>
            <div class="container-fluid">
                <a span style = "font-size: 20px; color: grey; text-decoration: none; margin-left:80px; margin-right:30px;"  asp-area="" asp-controller="Mockups" asp-action="Index"><b>Backend4</b></a>
                <a class="headlinks" asp-area="" asp-controller="Mockups" asp-action="Index">Home</a>
                <a class="headlinks" span style = "margin-left: 25px;"  asp-area="" asp-controller="Mockups" asp-action="Index">Mockups</a>
                <a class="headlinks" span style = "margin-left: 25px;"  asp-area="" asp-controller="Controls" asp-action="Index">Controls</a>
              @*  <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BackEnd1</a>
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                           @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>*@
                        </li>
                      @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Backend4 @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>